use_frameworks!

abstract_target 'Common' do
    pod 'BSWFoundation', :path => '/Users/piercifani/Workspace/BlurredSoftware/BSWFoundation'
    
    target 'BSWFoundationPlayground'
    target 'Tests' do
        inherit! :search_paths
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
