default_platform(:ios)

cocoapods(try_repo_update_on_error: true)
setup_jenkins

platform :ios do
  desc "Execute unit tests"
  lane :unit_tests do
    run_tests(
      workspace: "BSWFoundation.xcworkspace", 
      scheme: "BSWFoundationTests",
      devices: ["iPhone X"],
      )
  end
end
