name: Swift

on:
  push

jobs:
  apple-platforms-build:

    runs-on: ios

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift package clean; swift build
    - name: Run tests
      run: swift test

  android-build:
    # Runner must be macos-13, since lack of nested virtualization support on macos-14 prevents the Android emulator from working
    # see: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#limitations-for-arm64-macos-runners
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v1
