name: Swift

on:
  push

jobs:
  apple-platforms-build:

    runs-on: ios

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift package clean; swift build
    - name: Run tests
      run: swift test

  android-build:
    runs-on: ios
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v1
